[project]
name = "codex-py"
version = "0.1.0"
description = ""
authors = [
    {name = "RandomCivil",email = "theviperxie@gmail.com"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "langgraph (>=1.2.11,<2.0.0)",
    "openai (>=1.66.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "agent"}, {include = "llm"}, {include = "memory"}]
